---

- name: Install MariaDb
  yum: name=mariadb-server state=present

- name: Create installation directory
  file: path={{install_script_dir}}/mysql state=directory mode=0755

- name : Copy installation files
  copy: src=install/ dest={{install_script_dir}}/mysql

- name: Set file permissions
  file: 
    path={{install_script_dir}}/mysql/{{item}} 
    mode=0775
  with_items:
    - run-mysqld.sh
    - scripts/common.sh

- name: Configure Mariadb
  shell: 
    '{{install_script_dir}}/mysql/run-mysqld.sh >> {{install_script_dir}}/mysqld-install-log.txt
    creates={{install_script_dir}}/mysqld-install-log.txt'
  environment:
    MYSQL_LOWER_CASE_TABLE_NAMES: 1
    MYSQL_ROOT_PASSWORD: redhat

- name: Start Mariadb
  service: name=mariadb state=started

- name: Enable Mariadb
  service: name=mariadb enabled=yes
