---

- name: Create bpms quartz installation directory
  file: path={{install_script_dir}}/{{bpms_quartz_install_script_dir}} state=directory mode=0755

- name : Copy ddl files
  copy: src={{item}} dest={{install_script_dir}}/{{bpms_quartz_install_script_dir}}
  with_items:
    - quartz.properties

- name: Set file permissions
  file: path={{install_script_dir}}/{{bpms_quartz_install_script_dir}} recurse=true state=directory mode=0755